version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: go3_development
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:password@db/go3_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
