base_locale: en
locales: [en, fa]
data:
  read:
    - public/locales/%{locale}/*.json
  write:
    - - '{:}.*'
      - public/locales/%{locale}/%{0}.json
  yaml:
    write:
      line_width: -1
  json:
    write:
      indent: '  '
      space: ' '
      object_nl: "\n"
      array_nl: "\n"
search:
  paths:
    - frontend
  only:
    - "*.ts"
    - "*.tsx"
    - "*.vue"
  scanners:
    - - I18n::Tasks::Scanners::PatternScanner
      - pattern: |
          \b(?:t|I18n\.t|componentT|pageT|controller_t|model_t)\b\s*[\(\s]\s*["'](?<key>[^"']+)["']
ignore_missing:
  - 'errors.messages.*'
  - 'devise.*'
  - 'en'
  - 'fa'

ignore_unused:
  - 'activerecord.attributes.*'
  - 'activerecord.models.*'
  - 'errors.messages.*'
  - 'helpers.submit.*'
  - 'support.array.*'
  - 'number.format.*'
  - 'date.formats.*'
  - 'time.formats.*'
  - 'en'
  - 'fa'