import { Person, SmartToy } from '@mui/icons-material';
import { Avatar, Box, Typography } from '@mui/material';
import 'highlight.js/styles/github-dark.css'; // Premium dark theme for code blocks
import ReactMarkdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import remarkGfm from 'remark-gfm';
import type { Message } from './chat-types';

export interface ChatMessageProps {
  message: Message;
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isUser = message.role === 'user';

  return (
    <Box
      sx={{
        display: 'flex',
        gap: 2,
        alignItems: 'flex-start',
        flexDirection: isUser ? 'row-reverse' : 'row',
        animation: 'fadeIn 0.3s ease-out',
        '@keyframes fadeIn': {
          from: { opacity: 0, transform: 'translateY(10px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
      }}
    >
      <Avatar
        sx={{
          width: 36,
          height: 36,
          bgcolor: isUser ? 'action.selected' : 'primary.main',
          color: isUser ? 'text.secondary' : 'primary.contrastText',
          flexShrink: 0,
        }}
      >
        {isUser ? (
          <Person sx={{ fontSize: 20 }} />
        ) : (
          <SmartToy sx={{ fontSize: 20 }} />
        )}
      </Avatar>

      <Box
        sx={{
          maxWidth: '85%',
          px: 2.5,
          py: 1.5,
          borderRadius: isUser ? '24px 24px 4px 24px' : '24px 24px 24px 4px',
          bgcolor: isUser ? 'action.hover' : 'transparent',
          color: 'text.primary',
        }}
      >
        {isUser ? (
          <Typography
            variant="body1"
            sx={{ whiteSpace: 'pre-wrap', lineHeight: 1.6 }}
          >
            {message.content}
          </Typography>
        ) : (
          <Box
            sx={{
              '& p': { my: 1, lineHeight: 1.7 },
              '& p:first-of-type': { mt: 0 },
              '& p:last-child': { mb: 0 },
              '& a': {
                color: 'primary.main',
                textDecoration: 'none',
                '&:hover': { textDecoration: 'underline' },
              },
              // Default inline code style
              '& code:not([class*="language-"])': {
                bgcolor: 'action.selected',
                px: 0.5,
                py: 0.2,
                borderRadius: 1,
                fontFamily: 'monospace',
                fontSize: '0.875rem',
              },
              // Wrapper for the code block generated by rehype
              '& pre': {
                my: 2, // Some margin to breathe
                p: 2, // Internal padding for the background
                bgcolor: '#0d1117', // Match the Github dark theme background
                borderRadius: 2,
                overflowX: 'auto',
                fontFamily: 'monospace',
                fontSize: '0.875rem',
              },
              '& pre > code': {
                bgcolor: 'transparent', // Let parent pre background handle it
                p: 0,
              },
              '& blockquote': {
                borderLeft: '4px solid',
                borderColor: 'divider',
                pl: 2,
                ml: 0,
                color: 'text.secondary',
              },
              '& ul, & ol': { mt: 1, mb: 2, pl: 3 },
              '& li': { mb: 0.5 },
            }}
          >
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              rehypePlugins={[rehypeHighlight]}
            >
              {message.content}
            </ReactMarkdown>
          </Box>
        )}
      </Box>
    </Box>
  );
}
